### ISSUE TITLE
ERROR when action server launching

### ISSUE THREAD

**Issue by lunagava** [Woolfrey/server_serial_link#8]
I compiled all libraries (mujoco, robot_library, mujoco_interface, action_server) without errors inside a docker containers.

First run:
```
ros2 launch mujoco_interface velocity_mode.py
```
and the GUI opens. 

The second line in the terminal, instead gives me the following error:
```
root@luna-XPS-15-9500:/usr/local/src/server_serial_link/build# ros2 launch serial_link_action_server mujoco_velocity_control.py
[INFO] [launch]: All log files can be found below /root/.ros/log/2024-10-31-15-09-19-536241-luna-XPS-15-9500-21321
[INFO] [launch]: Default logging verbosity is set to INFO
[WARNING] [launch_ros.actions.node]: Parameter file path is not a file: /usr/local/src/server_serial_link/install/serial_link_action_server/share/serial_link_action_server/config/mujoco_velocity_control.yaml
[ERROR] [launch]: Caught exception in launch (see debug for traceback): executable 'mujoco_relay' not found on the libexec directory '/usr/local/src/server_serial_link/install/serial_link_action_server/lib/serial_link_action_server' 
```

The third line should work instead:
```
ros2 run serial_link_action_server demo_client 7
```

**Comment by lunagava** [comment]
@Woolfrey I hope you haven't forgotten this! If you would like, I could help by sharing the Dockerfile or setting up a call to show you sharing the screen without making you to reinstall!

**Comment by Woolfrey** [comment]
Hi @lunagava, which branch are you working from? I've been working on `devel`.

I've been trying to fix a lot of problems with the ROS2 communication before merging to the main.

**Comment by Woolfrey** [comment]
@lunagava:

In the `master` branch of `mujoco_ros2_interface`:
```
ros2 launch mujoco_interface velocity_mode.py
[INFO] [launch]: All log files can be found below /home/woolfrey/.ros/log/2024-12-12-15-06-09-300418-woolfrey-surface-studio-32927
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [mujoco_interface_node-1]: process started with pid [32928]
[mujoco_interface_node-1] [INFO] [1734015969.459570377] [mujoco_interface_node]: Control mode set to VELOCITY.
```

In the `devel` branch of `serial_link_action_server`:
```
ros2 launch serial_link_action_server mujoco_velocity_mode.py
[INFO] [launch]: All log files can be found below /home/woolfrey/.ros/log/2024-12-12-15-07-21-794255-woolfrey-surface-studio-33009
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [velocity_control_server-1]: process started with pid [33010]
[INFO] [mujoco_relay-2]: process started with pid [33012]
[velocity_control_server-1] [INFO] [KINEMATIC TREE] Successfully generated the 'iiwa14' robot model. It has 7 joints (reduced from 16).
[velocity_control_server-1] [INFO] [SERIAL LINK CONTROL] Controlling the 'link7' frame on the 'iiwa14' robot.
[velocity_control_server-1] [INFO] [1734016041.853343200] [iiwa14_model_updater]: Subscribing to 'joint_states' joint state topic.
[velocity_control_server-1] [INFO] [1734016041.856436945] [iiwa14_action_server]: 'track_joint_trajectory' action initiated. Publishing control output to 'joint_command_relay'.
[velocity_control_server-1] [INFO] [1734016041.857335885] [iiwa14_action_server]: 'track_cartesian_trajectory' action initiated. Publishing control output to 'joint_command_relay'.
```

And in another terminal:
```
ros2 run serial_link_action_server demo_client 7
[INFO] [1734016069.917050088] [serial_link_demo_client]: Enter a command. Type 'options' to a see a list.
```

**Comment by lunagava** [comment]
Hello @Woolfrey! Thanks for answering :) I was compiling the master branch for the action server!

This increased the error messages:

Starting >>> serial_link_action_server
--- stderr: serial_link_action_server                             
In file included from /usr/local/src/server_serial_link/src/velocity_control_server.cpp:9:
/usr/local/src/server_serial_link/include/ModelUpdater.h:27:22: error: ‘RobotLibrary’ has not been declared
   27 |         ModelUpdater(RobotLibrary::KinematicTree *model, const std::string &topicName = "joint_states");
      |                      ^~~~~~~~~~~~
/usr/local/src/server_serial_link/include/ModelUpdater.h:27:49: error: expected ‘)’ before ‘*’ token
   27 |         ModelUpdater(RobotLibrary::KinematicTree *model, const std::string &topicName = "joint_states");
      |                     ~                           ^~
      |                                                 )
/usr/local/src/server_serial_link/include/ModelUpdater.h:31:9: error: ‘RobotLibrary’ does not name a type
   31 |         RobotLibrary::KinematicTree *_model;                                                        ///< Pointer to robot model.
      |         ^~~~~~~~~~~~
In file included from /usr/local/src/server_serial_link/src/velocity_control_server.cpp:9:
/usr/local/src/server_serial_link/include/ModelUpdater.h:48:27: error: expected constructor, destructor, or type conversion before ‘(’ token
   48 | ModelUpdater::ModelUpdater(RobotLibrary::KinematicTree *model, const std::string &topicName)
      |                           ^
/usr/local/src/server_serial_link/include/ModelUpdater.h: In member function ‘void ModelUpdater::update(const JointState&)’:
/usr/local/src/server_serial_link/include/ModelUpdater.h:72:33: error: ‘_model’ was not declared in this scope; did you mean ‘modfl’?
   72 |     if(state.position.size() != _model->number_of_joints()
      |                                 ^~~~~~
      |                                 modfl
/usr/local/src/server_serial_link/include/ModelUpdater.h:83:15: error: ‘class ModelUpdater’ has no member named ‘_model’
   83 |         this->_model->update_state(Eigen::Map<const Eigen::VectorXd>(state.position.data(), state.position.size()),
      |               ^~~~~~
In file included from /usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:11,
                 from /usr/local/src/server_serial_link/src/velocity_control_server.cpp:10:
/usr/local/src/server_serial_link/include/server/ActionServerBase.h: At global scope:
/usr/local/src/server_serial_link/include/server/ActionServerBase.h:39:26: error: ‘RobotLibrary’ has not been declared
   39 |                          RobotLibrary::SerialLinkBase *controller,
      |                          ^~~~~~~~~~~~
/usr/local/src/server_serial_link/include/server/ActionServerBase.h:39:55: error: expected ‘,’ or ‘...’ before ‘*’ token
   39 |                          RobotLibrary::SerialLinkBase *controller,
      |                                                       ^
In file included from /usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:11,
                 from /usr/local/src/server_serial_link/src/velocity_control_server.cpp:10:
/usr/local/src/server_serial_link/include/server/ActionServerBase.h:56:9: error: ‘RobotLibrary’ does not name a type
   56 |         RobotLibrary::SerialLinkBase* _controller;                                                  ///< Pointer to the controller
      |         ^~~~~~~~~~~~
/usr/local/src/server_serial_link/include/server/ActionServerBase.h:116:44: error: ‘RobotLibrary’ has not been declared
  116 |                                            RobotLibrary::SerialLinkBase *controller,
      |                                            ^~~~~~~~~~~~
/usr/local/src/server_serial_link/include/server/ActionServerBase.h:116:73: error: expected ‘,’ or ‘...’ before ‘*’ token
  116 |                                            RobotLibrary::SerialLinkBase *controller,
      |                                                                         ^
/usr/local/src/server_serial_link/include/server/ActionServerBase.h: In constructor ‘ActionServerBase<Action>::ActionServerBase(std::shared_ptr<rclcpp::Node>, int)’:
/usr/local/src/server_serial_link/include/server/ActionServerBase.h:121:57: error: ‘controller’ was not declared in this scope
  121 |                                              _numJoints(controller->model()->number_of_joints()),
      |                                                         ^~~~~~~~~~
/usr/local/src/server_serial_link/include/server/ActionServerBase.h:122:46: error: class ‘ActionServerBase<Action>’ does not have any field named ‘_controller’
  122 |                                              _controller(controller),
      |                                              ^~~~~~~~~~~
/usr/local/src/server_serial_link/include/server/ActionServerBase.h:123:55: error: ‘padlock’ was not declared in this scope; did you mean ‘_padlock’?
  123 |                                              _padlock(padlock)
      |                                                       ^~~~~~~
      |                                                       _padlock
/usr/local/src/server_serial_link/include/server/ActionServerBase.h:130:9: error: ‘actionName’ was not declared in this scope
  130 |         actionName,
      |         ^~~~~~~~~~
/usr/local/src/server_serial_link/include/server/ActionServerBase.h:142:71: error: ‘controlTopicName’ was not declared in this scope
  142 |     _jointCommandPublisher = _node->create_publisher<JointCommandMsg>(controlTopicName, 1);         // Create publisher for joint commands
      |                                                                       ^~~~~~~~~~~~~~~~
In file included from /usr/local/src/server_serial_link/src/velocity_control_server.cpp:10:
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h: At global scope:
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:35:34: error: ‘RobotLibrary’ has not been declared
   35 |                                  RobotLibrary::SerialLinkBase *controller,
      |                                  ^~~~~~~~~~~~
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:35:63: error: expected ‘,’ or ‘...’ before ‘*’ token
   35 |                                  RobotLibrary::SerialLinkBase *controller,
      |                                                               ^
In file included from /usr/local/src/server_serial_link/src/velocity_control_server.cpp:10:
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:46:9: error: ‘RobotLibrary’ does not name a type
   46 |         RobotLibrary::CartesianSpline _trajectory;                                                  ///< Trajectory generator
      |         ^~~~~~~~~~~~
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:72:52: error: ‘RobotLibrary’ has not been declared
   72 |                                                    RobotLibrary::SerialLinkBase *controller,
      |                                                    ^~~~~~~~~~~~
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:72:81: error: expected ‘,’ or ‘...’ before ‘*’ token
   72 |                                                    RobotLibrary::SerialLinkBase *controller,
      |                                                                                 ^
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h: In constructor ‘TrackCartesianTrajectory::TrackCartesianTrajectory(std::shared_ptr<rclcpp::Node>, int)’:
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:78:57: error: ‘controller’ was not declared in this scope
   78 |                                                         controller,
      |                                                         ^~~~~~~~~~
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:79:57: error: ‘padlock’ was not declared in this scope; did you mean ‘_padlock’?
   79 |                                                         padlock,
      |                                                         ^~~~~~~
      |                                                         _padlock
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:80:57: error: ‘actionName’ was not declared in this scope
   80 |                                                         actionName,
      |                                                         ^~~~~~~~~~
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:81:57: error: ‘controlTopicName’ was not declared in this scope
   81 |                                                         controlTopicName)
      |                                                         ^~~~~~~~~~~~~~~~
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:72:66: warning: unused parameter ‘SerialLinkBase’ [-Wunused-parameter]
   72 |                                                    RobotLibrary::SerialLinkBase *controller,
      |                                                    ~~~~~~~~~~~~~~^~~~~~~~~~~~~~
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h: In member function ‘virtual rclcpp_action::GoalResponse TrackCartesianTrajectory::process_request(const GoalUUID&, std::shared_ptr<const serial_link_action_server::action::TrackCartesianTrajectory_Goal_<std::allocator<void> > >)’:
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:107:17: error: ‘RobotLibrary’ was not declared in this scope
  107 |     std::vector<RobotLibrary::Pose> poses;                                                          // Poses that make up the trajectory spline
      |                 ^~~~~~~~~~~~
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:107:35: error: template argument 1 is invalid
  107 |     std::vector<RobotLibrary::Pose> poses;                                                          // Poses that make up the trajectory spline
      |                                   ^
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:107:35: error: template argument 2 is invalid
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:109:11: error: request for member ‘reserve’ in ‘poses’, which is of non-class type ‘int’
  109 |     poses.reserve(request->points.size()+1);                                                        // Reserve space for efficiency
      |           ^~~~~~~
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:111:11: error: request for member ‘emplace_back’ in ‘poses’, which is of non-class type ‘int’
  111 |     poses.emplace_back(_controller->endpoint_pose());                                               // First pose is current endpoint
      |           ^~~~~~~~~~~~
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:111:24: error: ‘_controller’ was not declared in this scope
  111 |     poses.emplace_back(_controller->endpoint_pose());                                               // First pose is current endpoint
      |                        ^~~~~~~~~~~
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:128:44: error: request for member ‘emplace_back’ in ‘poses’, which is of non-class type ‘int’
  128 |             if(point.reference == 0) poses.emplace_back(RobotLibrary::Pose(translation,quaternion));// In base frame
      |                                            ^~~~~~~~~~~~
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:128:57: error: ‘RobotLibrary’ is not a class, namespace, or enumeration
  128 |             if(point.reference == 0) poses.emplace_back(RobotLibrary::Pose(translation,quaternion));// In base frame
      |                                                         ^~~~~~~~~~~~
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:129:44: error: request for member ‘emplace_back’ in ‘poses’, which is of non-class type ‘int’
  129 |        else if(point.reference == 1) poses.emplace_back(poses.back()*RobotLibrary::Pose(translation,quaternion)); // In current endpoint frame; transform to base
      |                                            ^~~~~~~~~~~~
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:129:63: error: request for member ‘back’ in ‘poses’, which is of non-class type ‘int’
  129 |        else if(point.reference == 1) poses.emplace_back(poses.back()*RobotLibrary::Pose(translation,quaternion)); // In current endpoint frame; transform to base
      |                                                               ^~~~
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:129:70: error: ‘RobotLibrary’ is not a class, namespace, or enumeration
  129 |        else if(point.reference == 1) poses.emplace_back(poses.back()*RobotLibrary::Pose(translation,quaternion)); // In current endpoint frame; transform to base
      |                                                                      ^~~~~~~~~~~~
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:132:33: error: request for member ‘back’ in ‘poses’, which is of non-class type ‘int’
  132 |             translation = poses.back().translation() + translation;                                 // Add the translation
      |                                 ^~~~
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:133:33: error: request for member ‘back’ in ‘poses’, which is of non-class type ‘int’
  133 |             quaternion  = poses.back().quaternion()*quaternion;                                     // Add the rotation
      |                                 ^~~~
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:134:19: error: request for member ‘emplace_back’ in ‘poses’, which is of non-class type ‘int’
  134 |             poses.emplace_back(RobotLibrary::Pose(translation,quaternion));
      |                   ^~~~~~~~~~~~
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:134:32: error: ‘RobotLibrary’ is not a class, namespace, or enumeration
  134 |             poses.emplace_back(RobotLibrary::Pose(translation,quaternion));
      |                                ^~~~~~~~~~~~
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:152:9: error: ‘_trajectory’ was not declared in this scope
  152 |         _trajectory = RobotLibrary::CartesianSpline(poses,times,_controller->endpoint_velocity());
      |         ^~~~~~~~~~~
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:152:23: error: ‘RobotLibrary’ is not a class, namespace, or enumeration
  152 |         _trajectory = RobotLibrary::CartesianSpline(poses,times,_controller->endpoint_velocity());
      |                       ^~~~~~~~~~~~
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h: In member function ‘virtual void TrackCartesianTrajectory::execute(std::shared_ptr<rclcpp_action::ServerGoalHandle<serial_link_action_server::action::TrackCartesianTrajectory> >)’:
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:174:27: error: ‘_controller’ was not declared in this scope
  174 |     rclcpp::Rate loopRate(_controller->frequency());
      |                           ^~~~~~~~~~~
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:234:45: error: ‘_trajectory’ was not declared in this scope
  234 |                      desiredAcceleration] = _trajectory.query_state(elapsedTime);                   // Query desired state for given time
      |                                             ^~~~~~~~~~~
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:253:9: error: ‘RobotLibrary’ has not been declared
  253 |         RobotLibrary::Pose actualPose = _controller->endpoint_pose();
      |         ^~~~~~~~~~~~
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:256:66: error: ‘RobotLibrary’ does not name a type
  256 |         auto update_pose_feedback = [](auto &feedbackPose, const RobotLibrary::Pose &pose)
      |                                                                  ^~~~~~~~~~~~
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:265:10: error: expected ‘)’ before ‘;’ token
  265 |         };
      |          ^
      |          )
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:256:39: note: to match this ‘(’
  256 |         auto update_pose_feedback = [](auto &feedbackPose, const RobotLibrary::Pose &pose)
      |                                       ^
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h: In lambda function:
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:265:10: error: expected ‘{’ before ‘;’ token
  265 |         };
      |          ^
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:256:46: warning: unused parameter ‘feedbackPose’ [-Wunused-parameter]
  256 |         auto update_pose_feedback = [](auto &feedbackPose, const RobotLibrary::Pose &pose)
      |                                        ~~~~~~^~~~~~~~~~~~
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h: In member function ‘virtual void TrackCartesianTrajectory::execute(std::shared_ptr<rclcpp_action::ServerGoalHandle<serial_link_action_server::action::TrackCartesianTrajectory> >)’:
/usr/local/src/server_serial_link/include/server/TrackCartesianTrajectory.h:277:54: error: ‘actualPose’ was not declared in this scope
  277 |         update_pose_feedback(_feedback->actual.pose, actualPose);
      |                                                      ^~~~~~~~~~
In file included from /usr/local/src/server_serial_link/src/velocity_control_server.cpp:11:
/usr/local/src/server_serial_link/include/server/TrackJointTrajectory.h: At global scope:
/usr/local/src/server_serial_link/include/server/TrackJointTrajectory.h:35:30: error: ‘RobotLibrary’ has not been declared
   35 |                              RobotLibrary::SerialLinkBase *controller,
      |                              ^~~~~~~~~~~~
/usr/local/src/server_serial_link/include/server/TrackJointTrajectory.h:35:59: error: expected ‘,’ or ‘...’ before ‘*’ token
   35 |                              RobotLibrary::SerialLinkBase *controller,
      |                                                           ^
In file included from /usr/local/src/server_serial_link/src/velocity_control_server.cpp:11:
/usr/local/src/server_serial_link/include/server/TrackJointTrajectory.h:44:9: error: ‘RobotLibrary’ does not name a type
   44 |         RobotLibrary::SplineTrajectory _trajectory;                                                 ///< Trajectory object
      |         ^~~~~~~~~~~~
/usr/local/src/server_serial_link/include/server/TrackJointTrajectory.h:70:44: error: ‘RobotLibrary’ has not been declared
   70 |                                            RobotLibrary::SerialLinkBase *controller,
      |                                            ^~~~~~~~~~~~
/usr/local/src/server_serial_link/include/server/TrackJointTrajectory.h:70:73: error: expected ‘,’ or ‘...’ before ‘*’ token
   70 |                                            RobotLibrary::SerialLinkBase *controller,
      |                                                                         ^
/usr/local/src/server_serial_link/include/server/TrackJointTrajectory.h: In constructor ‘TrackJointTrajectory::TrackJointTrajectory(std::shared_ptr<rclcpp::Node>, int)’:
/usr/local/src/server_serial_link/include/server/TrackJointTrajectory.h:77:49: error: ‘controller’ was not declared in this scope
   77 |                                                 controller,
      |                                                 ^~~~~~~~~~
/usr/local/src/server_serial_link/include/server/TrackJointTrajectory.h:78:49: error: ‘padlock’ was not declared in this scope; did you mean ‘_padlock’?
   78 |                                                 padlock,
      |                                                 ^~~~~~~
      |                                                 _padlock
/usr/local/src/server_serial_link/include/server/TrackJointTrajectory.h:79:49: error: ‘actionName’ was not declared in this scope
   79 |                                                 actionName,
      |                                                 ^~~~~~~~~~
/usr/local/src/server_serial_link/include/server/TrackJointTrajectory.h:80:49: error: ‘controlTopicName’ was not declared in this scope
   80 |                                                 controlTopicName
      |                                                 ^~~~~~~~~~~~~~~~
/usr/local/src/server_serial_link/include/server/TrackJointTrajectory.h:70:58: warning: unused parameter ‘SerialLinkBase’ [-Wunused-parameter]
   70 |                                            RobotLibrary::SerialLinkBase *controller,
      |                                            ~~~~~~~~~~~~~~^~~~~~~~~~~~~~
/usr/local/src/server_serial_link/include/server/TrackJointTrajectory.h: In member function ‘virtual rclcpp_action::GoalResponse TrackJointTrajectory::process_request(const GoalUUID&, std::shared_ptr<const serial_link_action_server::action::TrackJointTrajectory_Goal_<std::allocator<void> > >)’:
/usr/local/src/server_serial_link/include/server/TrackJointTrajectory.h:127:28: error: ‘_controller’ was not declared in this scope
  127 |     positions.emplace_back(_controller->model()->joint_positions());                                // Start trajectory from current position
      |                            ^~~~~~~~~~~
/usr/local/src/server_serial_link/include/server/TrackJointTrajectory.h:160:9: error: ‘_trajectory’ was not declared in this scope
  160 |         _trajectory = RobotLibrary::SplineTrajectory(positions, times, _controller->model()->joint_velocities());
      |         ^~~~~~~~~~~
/usr/local/src/server_serial_link/include/server/TrackJointTrajectory.h:160:23: error: ‘RobotLibrary’ has not been declared
  160 |         _trajectory = RobotLibrary::SplineTrajectory(positions, times, _controller->model()->joint_velocities());
      |                       ^~~~~~~~~~~~
/usr/local/src/server_serial_link/include/server/TrackJointTrajectory.h: In member function ‘virtual void TrackJointTrajectory::execute(std::shared_ptr<rclcpp_action::ServerGoalHandle<serial_link_action_server::action::TrackJointTrajectory> >)’:
/usr/local/src/server_serial_link/include/server/TrackJointTrajectory.h:183:27: error: ‘_controller’ was not declared in this scope
  183 |     rclcpp::Rate loopRate(_controller->frequency());
      |                           ^~~~~~~~~~~
/usr/local/src/server_serial_link/include/server/TrackJointTrajectory.h:230:45: error: ‘_trajectory’ was not declared in this scope
  230 |                      desiredAcceleration] = _trajectory.query_state(elapsedTime);
      |                                             ^~~~~~~~~~~
/usr/local/src/server_serial_link/src/velocity_control_server.cpp: In function ‘int main(int, char**)’:
/usr/local/src/server_serial_link/src/velocity_control_server.cpp:31:9: error: ‘RobotLibrary’ has not been declared
   31 |         RobotLibrary::KinematicTree robotModel(urdfLocation);                                       // Create the robot model
      |         ^~~~~~~~~~~~
/usr/local/src/server_serial_link/src/velocity_control_server.cpp:32:9: error: ‘RobotLibrary’ has not been declared
   32 |         RobotLibrary::SerialKinematicControl controller(&robotModel, endpointName, frequency);      // Create controller, attach model
      |         ^~~~~~~~~~~~
/usr/local/src/server_serial_link/src/velocity_control_server.cpp:33:9: error: ‘controller’ was not declared in this scope
   33 |         controller.set_joint_gains(kp, 1.0);                                                        // Set control gains
      |         ^~~~~~~~~~
/usr/local/src/server_serial_link/src/velocity_control_server.cpp:36:65: error: ‘robotModel’ was not declared in this scope
   36 |         auto modelUpdaterNode = std::make_shared<ModelUpdater>(&robotModel);                        // Reads & updates joint state
      |                                                                 ^~~~~~~~~~
/usr/local/src/server_serial_link/src/velocity_control_server.cpp:24:16: warning: unused variable ‘frequency’ [-Wunused-variable]
   24 |         double frequency = paramNode->declare_parameter<double>("frequency", 500.0);
      |                ^~~~~~~~~
gmake[2]: *** [CMakeFiles/velocity_control_server.dir/build.make:76: CMakeFiles/velocity_control_server.dir/src/velocity_control_server.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:597: CMakeFiles/velocity_control_server.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< serial_link_action_server [5.29s, exited with code 2]

Summary: 0 packages finished [5.54s]
  1 package failed: serial_link_action_server
  1 package had stderr output: serial_link_action_server

**Comment by Woolfrey** [comment]
> Hello @Woolfrey! Thanks for answering :) I was compiling the master branch for the action server!
> 
> This increased the error messages: [error_server.txt](https://github.com/user-attachments/files/18124792/error_server.txt)

@lunagava, try pulling the `master` branch of `RobotLibrary` and reinstalling it. I added a namespace to everything. That should fix most problems.

@ssutjipto, @anubhav-dogra could you guys try:
1. Pulling the latest `master` branch of RobotLibrary, build, and install
2. Pull the `master` branch of the mujoco_ros2_interface
3. Pull the `devel` branch of the serial_link_action_server, then

and see if you can get it to run as I did in the above post?

@ssutjipto, could you test it quickly before our meeting on Monday? Thanks!

**Comment by lunagava** [comment]
@Woolfrey [RobotLibrary](https://github.com/Woolfrey/software_robot_library) the last change is to 3 weeks ago!

Cloning and reinstalling again got me errors to compile.
![Screenshot from 2024-12-13 15-12-25](https://github.com/user-attachments/assets/3d9b7c3e-97c4-4574-8e25-5596ba501a8c)

**Comment by lunagava** [comment]
Thanks @Woolfrey  for the patch! It finally worked!

https://github.com/user-attachments/assets/be3f8673-90f3-42c2-a530-c1d95847478f

**Comment by Woolfrey** [comment]
Ottimo!

I still need to fix the singularity issue, load pre-defined trajectories, and other little features, but good to see the core is working.

@lunagava do you send a twist vector to control the end-effector? I can write an action for that.

**Comment by lunagava** [comment]
My goal is to do image-based visual-servoing, so I would like to send to the end-effector cartesian linear and angular velocities v_x, v_y, v_z, roll, pitch and yaw, computed from PID. It would be useful to have the action available. Otherwise, I was thinking of calling the resolve_endpoint_motion() of the robot library.

@Woolfrey I need a suggestion regarding how to use the action-server with the real-robot! Don't I need the Mujoco interface right?

**Comment by Woolfrey** [comment]
Hey @lunagava,

- If you're doing image-based visual servoing in the _image_ plane, it is probably best to write a custom controller in `RobotLibrary`, and a custom ROS2 action to wrap around it. But this will take time...!
- If you're sending linear & angular velocities (a twist vector), I can write a simple action server to follow it. You could use this in the short-term (at the moment I only implemented trajectory tracking to test everything works).
- The MuJoCo interface is just for testing / simulation purposes. You should be able to swap out the MuJoCo simulation for a real robot by connecting the correct topics:
     - Send the '/joint_commands' topic to the real robot.
     - Ensure the `model_updater` node is subscribed to the `/joint_state` topic coming from the real robot.
